### ISSUE TITLE
Xcode 6.4 Analyser warning - SBFullStatistics.m:38:5: Key argument to 'setObject:forKey:' cannot be nil

### ISSUE THREAD

**Issue by paulz** [stig/Statistics#4]
Select Product, Analyze in Xcode menu, see the following warnings. Looks like it might crash in frequencyDistributionWithBuckets:cumulative, fortunately I am not using that method.

/Pods/Statistics/Classes/SBFullStatistics.m:38:5: Key argument to 'setObject:forKey:' cannot be nil
/Pods/Statistics/Classes/SBFullStatistics.m:220:10: Loop body skipped when collection is empty
/Pods/Statistics/Classes/SBFullStatistics.m:225:10: Loop body skipped when collection is empty
/Pods/Statistics/Classes/SBFullStatistics.m:234:10: Entering loop body
/Pods/Statistics/Classes/SBFullStatistics.m:239:13: Value assigned to 'b'
/Pods/Statistics/Classes/SBFullStatistics.m:240:17: Assuming 'b' is nil
/Pods/Statistics/Classes/SBFullStatistics.m:234:5: Looping back to the head of the loop
/Pods/Statistics/Classes/SBFullStatistics.m:234:10: Entering loop body
/Pods/Statistics/Classes/SBFullStatistics.m:237:31: Passing nil object reference via 2nd parameter 'key'
/Pods/Statistics/Classes/SBFullStatistics.m:237:4: Calling 'incrementValueForKey'
/Pods/Statistics/Classes/SBFullStatistics.m:32:1: Entered call from 'frequencyDistributionWithBuckets:cumulative:'
/Pods/Statistics/Classes/SBFullStatistics.m:35:13: Assuming 'value' is nil
/Pods/Statistics/Classes/SBFullStatistics.m:38:5: Key argument to 'setObject:forKey:' cannot be nil

Thank you for the great pod!

**Comment by stig** [comment]
Thanks for the report. Would you be interested in providing a pull request that fixes this problem?

Stig
